<?php
# This file was automatically generated by the MediaWiki 1.19.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Вікі Фаланстэра";
$wgMetaNamespace = "Вікі_Фаланстэра";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/w";
$wgScriptExtension  = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "https://wiki.falanster.info";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/common/images/Falanster_wiki_logo.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "apache@wiki.falanster.info";
$wgPasswordSender   = "apache@wiki.falanster.info";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "wiki_falanster";
$wgDBuser           = "wiki_falanster";
$wgDBpassword       = "On6BAURVVPxXlJpH";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "ru";

$wgSecretKey = "6ad10543882e183b5611c1aa19032c3efbc1b40108ab9c4e86b9a28c739f5f2b";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "fd7c266cfa45e639";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "http://creativecommons.org/licenses/by-sa/3.0/";
$wgRightsText = "Attribution-Share-Alike 3.0 Unported";
$wgRightsIcon = "https://licensebuttons.net/l/by-sa/3.0/88x31.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;



# End of automatically generated settings.
# Add more configuration options below.

# Restrict Anonymous Editing
$wgGroupPermissions['*']['edit'] = false;


#require_once "$IP/extensions/ConfirmAccount/ConfirmAccount.php";
#$wgAccountRequestMinWords = 0;


require_once "$IP/extensions/ConfirmEdit/ConfirmEdit.php";

require_once( "$IP/extensions/ConfirmEdit/QuestyCaptcha.php");
$wgCaptchaClass = 'QuestyCaptcha';
$arr = array (
        "Napishite v teskstovom pole ciframi chislo sorok dva" => "42",
        "Napishite v teskstovom pole ciframi chislo trista dvadcat odin" => "321",
        "Napishite v teskstovom pole ciframi chislo minus odin" => "-1",
        "Napishite v teskstovom pole ciframi chislo pyatsot" => "500",
);

foreach ( $arr as $key => $value ) {
        $wgCaptchaQuestions[] = array( 'question' => $key, 'answer' => $value );
}

#require_once "$IP/extensions/ConfirmEdit/ReCaptcha.php";
#$wgCaptchaClass = 'ReCaptcha';
#$wgCaptchaTriggers['addurl'] = false; 
#$wgReCaptchaPublicKey = '6LeAsOYSAAAAAFPi_3Tsv6IkfTqkIw-w4BaC8Kh3';
#$wgReCaptchaPrivateKey = '6LeAsOYSAAAAAFk-mEaA3WLsee_LS6oE8JPHdKhp';


require_once( "$IP/extensions/Nuke/Nuke.php" );

$wgFavicon = "$wgScriptPath/favicon.ico";

require_once "$IP/extensions/UserMerge/UserMerge.php";
// By default nobody can use this function, enable for bureaucrat?
$wgGroupPermissions['bureaucrat']['usermerge'] = true;
 
// optional: default is array( 'sysop' )
//$wgUserMergeProtectedGroups = array('groupname');

define("NS_SCHOOL", 500);
$wgExtraNamespaces[NS_SCHOOL] = "School";
$wgNamespacesWithSubpages[NS_SCHOOL] = true;

$wgFileExtensions = array_merge($wgFileExtensions, array('png', 'gif', 'jpg', 'jpeg', 'doc', 'xls', 'mpp', 'pdf', 'pptx', 'zip', 'ppt', 'doc', 'gz', 'docx', 'xlsx', 'svg' ));



// added short links
$wgScriptPath = "/w"; 
$wgArticlePath = "/wiki/$1";  
$wgUsePathInfo = true;
require_once "$IP/skins/CologneBlue/CologneBlue.php";
require_once "$IP/skins/Modern/Modern.php";
require_once "$IP/skins/MonoBook/MonoBook.php";
require_once "$IP/skins/Vector/Vector.php";
#wfLoadExtension( 'WikiEditor' );  
require_once "$IP/extensions/WikiEditor/WikiEditor.php";

# Enables use of WikiEditor by default but still allow users to disable it in preferences
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;

# Displays the Preview and Changes tabs
$wgDefaultUserOptions['wikieditor-preview'] = 1;

# Displays the Publish and Cancel buttons on the top right side
$wgDefaultUserOptions['wikieditor-publish'] = 1;

#require_once "$IP/extensions/ShortUrl/ShortUrl.php";      
